spring.config.import=optional:file:./.env[.properties]
spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:15432/passkey-demo
spring.datasource.username=passkey-demo
spring.datasource.password=passkey-demo
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
jwt.secret=4261656C64756E67
jwt.expiration=900000
webauthn.origin.url=localhost
webauthn.rp.id=me
spring.web.error.include-message=always
